[package]
name = "waggle-ebpf"
description = "eBPF-side library for waggle tests: arrange/act/assert program macros, assertions and test logging"
categories = ["development-tools::testing", "network-programming", "no-std"]
keywords.workspace = true

edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
waggle-shared = { workspace = true }
waggle-macros = { workspace = true }

aya-ebpf = { workspace = true }
network-types = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true, default-features = false }
