[package]
name = "xtask"
publish = false

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
cargo_metadata = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[[bin]]
name = "xtask"
path = "src/main.rs"
