use gladia::{EbpfObject, Res, run_ebpf_test};

// Generated by `just build-ebpf` (`cargo xtask build-ebpf -p <pkg> -o <file>`).
include!("../../../target/ebpf-objects/ebpf-programs.rs");
include!("../../../target/ebpf-objects/ebpf-test-programs.rs");

#[test]
#[ignore = "requires CAP_NET_ADMIN/CAP_SYS_ADMIN and a writable /run/netns"]
fn ebpf_test_runner() -> Res<()> {
    run_ebpf_test(&PROGRAMS, &TEST_PROGRAMS)
}
