[package]
name = "waggle"
publish = false

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
waggle-shared = { path = "../waggle-shared", features = ["std"] }

anyhow = { workspace = true }
aya = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true, features = ["std"] }
object = "0.37"
