[package]
name = "waggle"
description = "Test framework for eBPF programs: loads waggle test programs and runs them in the kernel with BPF_PROG_TEST_RUN"
categories = ["development-tools::testing", "network-programming"]
keywords.workspace = true

edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
waggle-shared = { workspace = true, features = ["user"] }

aya = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
syn = { version = "3", features = ["full", "visit"] }
thiserror = { workspace = true, features = ["std"] }

[dev-dependencies]
anyhow = { workspace = true }
object = "0.37"
