use std::{
    collections::BTreeMap,
    io::Write,
    path::PathBuf,
    process::{Command, Stdio},
};

use aya::{
    Ebpf, EbpfLoader, TestRun, TestRunOptions,
    maps::{Array, MapData, ProgramArray},
    programs::SchedClassifier,
};
use regex::Regex;
use waggle_shared::{
    FROM_CONTAINER, FROM_HOST, FROM_NETDEV, FROM_OVERLAY, FROM_WIREGUARD, ScapyAssert,
    TEST_RESULT_MAP_SIZE, TO_CONTAINER, TO_HOST, TO_NETDEV, TO_OVERLAY, TO_WIREGUARD, TestStatus,
    tlv_reader,
};

use crate::{Res, TestRunnerError, ebpf_test_runner::run_ebpf_test, report};

const ENTRY_CALL_PROGRAMS: &[(u32, &str)] = &[
    (FROM_CONTAINER, "from_container"),
    (TO_CONTAINER, "to_container"),
    (FROM_HOST, "from_host"),
    (TO_HOST, "to_host"),
    (FROM_NETDEV, "from_netdev"),
    (TO_NETDEV, "to_netdev"),
    (FROM_OVERLAY, "from_overlay"),
    (TO_OVERLAY, "to_overlay"),
    (FROM_WIREGUARD, "from_wireguard"),
    (TO_WIREGUARD, "to_wireguard"),
];

const PIN_DIR: &str = "/sys/fs/bpf/waggle";

// Generated by `just build-ebpf` (`cargo xtask build-ebpf -p <pkg> -o <file>`).
include!("../../target/ebpf-objects/ebpf-programs.rs");
include!("../../target/ebpf-objects/ebpf-test-programs.rs");

#[test]
#[ignore = "requires CAP_NET_ADMIN/CAP_SYS_ADMIN and a writable /run/netns"]
fn ebpf_test_runner() -> Res<()> {
    run_ebpf_test(
        PIN_DIR,
        PROGRAMS.bytes,
        TEST_PROGRAMS.bytes,
        ENTRY_CALL_PROGRAMS,
    )
}
