[package]
name = "sarena-ebpf-test-framework"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
sarena-shared-test = { path = "../sarena-shared-test", default-features = false }

aya-ebpf = { workspace = true }
network-types = { workspace = true }
serde = { workspace = true }

[build-dependencies]
which = { workspace = true }
