use gladia::{EbpfObject, Res, run_ebpf_test};
use gladia_shared::{
    FROM_CONTAINER, FROM_HOST, FROM_NETDEV, FROM_OVERLAY, FROM_WIREGUARD, STRING_SIZE,
    TO_CONTAINER, TO_HOST, TO_NETDEV, TO_OVERLAY, TO_WIREGUARD, TestEntryCall,
};
use object::{Object as _, ObjectSection as _};

const ENTRY_CALL_PROGRAMS: &[(u32, &str)] = &[
    (FROM_CONTAINER, "from_container"),
    (TO_CONTAINER, "to_container"),
    (FROM_HOST, "from_host"),
    (TO_HOST, "to_host"),
    (FROM_NETDEV, "from_netdev"),
    (TO_NETDEV, "to_netdev"),
    (FROM_OVERLAY, "from_overlay"),
    (TO_OVERLAY, "to_overlay"),
    (FROM_WIREGUARD, "from_wireguard"),
    (TO_WIREGUARD, "to_wireguard"),
];

const PIN_DIR: &str = "/sys/fs/bpf/gladia";

// Generated by `just build-ebpf` (`cargo xtask build-ebpf -p <pkg> -o <file>`).
include!("../../target/ebpf-objects/ebpf-programs.rs");
include!("../../target/ebpf-objects/ebpf-test-programs.rs");

#[test]
#[ignore = "requires CAP_NET_ADMIN/CAP_SYS_ADMIN and a writable /run/netns"]
fn ebpf_test_runner() -> Res<()> {
    find_entry_calls(TEST_PROGRAMS.bytes).expect("");

    run_ebpf_test(
        PIN_DIR,
        PROGRAMS.bytes,
        TEST_PROGRAMS.bytes,
        ENTRY_CALL_PROGRAMS,
    )
}

fn find_entry_calls(data: &[u8]) -> anyhow::Result<()> {
    let file = object::File::parse(data)?;
    for section in file.sections() {
        if section.name()? == ".gladia_tail_call_section" {
            let metadata = section.data()?;
            let little_endian = file.is_little_endian();
            let mut reader = Reader::new(metadata, little_endian);

            // Every source file with tail calls adds its own header, placed back to back.
            while !reader.is_empty() {
                let version = reader.read_u32()?;
                let file_name = reader.read_str(STRING_SIZE)?;
                println!("file_name: {file_name}");
                if version != 1 {
                    eprintln!("{file_name}: unsupported version {version}, expected 1");
                }

                let size = reader.read_u32()? as usize;
                let expected_size = core::mem::size_of::<TestEntryCall>();
                if size != expected_size {
                    anyhow::bail!("{file_name}: entry size is {size}, expected {expected_size}");
                }

                let count = reader.read_u32()? as usize;

                for _ in 0..count {
                    let index = reader.read_u32()?;
                    let name = reader.read_str(STRING_SIZE)?;
                    println!("{index} --> {name}")
                }
            }
        }
    }
    Ok(())
}

use std::io::{self, Cursor, Read};

struct Reader<'a> {
    cursor: Cursor<&'a [u8]>,
    little_endian: bool,
}

impl<'a> Reader<'a> {
    fn new(data: &'a [u8], little_endian: bool) -> Self {
        Self {
            cursor: Cursor::new(data),
            little_endian,
        }
    }

    fn is_empty(&self) -> bool {
        self.cursor.position() as usize >= self.cursor.get_ref().len()
    }

    fn read_u32(&mut self) -> io::Result<u32> {
        let mut buf = [0u8; 4];
        self.cursor.read_exact(&mut buf)?;
        Ok(if self.little_endian {
            u32::from_le_bytes(buf)
        } else {
            u32::from_be_bytes(buf)
        })
    }

    fn read_str(&mut self, max_size: usize) -> io::Result<&'a str> {
        let start = self.cursor.position() as usize;
        let data = self.cursor.get_ref();

        let end = start
            .checked_add(max_size)
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "size overflow"))?;

        if end > data.len() {
            return Err(io::Error::new(
                io::ErrorKind::UnexpectedEof,
                "not enough data",
            ));
        }

        let bytes = &data[start..end];
        let len = bytes.iter().position(|&b| b == 0).unwrap_or(max_size);
        self.cursor.set_position(end as u64);

        std::str::from_utf8(&bytes[..len])
            .map_err(|_| io::Error::new(io::ErrorKind::InvalidData, "invalid UTF-8"))
    }
}
